Algoritmo "algoritimo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2023
Var
// Seção de Declarações das variáveis 
A,B,soma:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite 1 numero: ")
leia(A)
escreval("digite 1 numero: ")
leia(B)
soma <- A+B
escreval("A soma é = ",soma)

Fimalgoritmo