Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2023
Var
// Seção de Declarações das variáveis 
 numero:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um numero: ")
leia(numero)

se(numero>0)entao

escreva("O numero",numero,"é positivo")

Fimalgoritmo